include(
    ":android",
    ":common:core",
    ":common:entity",
    ":common:domain",
    ":common:source:remote",
    ":common:feature:validation",
    ":common:feature:login",
    ":common:feature:signin:signin-impl",
    ":common:feature:signin:signin-api"
)
